### PR TITLE
change FieldValue::String representation

### LINKED ISSUE #4: Failed to Parse Deadlock demofile
Reproduce:
1. Download demo file: `wget http://replay187.valve.net/1422450/40142933_2060907135.dem.bz2`
    Uploading a copy of it here: <https://drive.google.com/drive/folders/119Z0-rfIYe5U-yxzsB1bcXz9kZXWDHVi?usp=sharing>
2. Decompress `bzip2 -d 40142933_2060907135.dem.bz2`
3. Go to: https://blukai.github.io/haste-inspector/
4. Select the decompressed demo file

Image

I guess it's cause of the non utf8 strings in there since the newest patch, no idea why there are non utf8 strings, but maybe you know.

### PR DESCRIPTION
**Pull request by blukai**
fixes #4

code-comments should explain all the reasoning.

@raimannma utf8 mystery solved. thoughts on the change?

note that i have not updated haste-inspector, can do post-merge, but here's a patch for haste-inspector if you want to try it locally (you'll also have to change haste's git rev in cargo.toml and rebuild wasm).

```diff
diff --git a/crates/haste-wasm/src/lib.rs b/crates/haste-wasm/src/lib.rs
index 657631f..5333262 100644
--- a/crates/haste-wasm/src/lib.rs
+++ b/crates/haste-wasm/src/lib.rs
@@ -121,10 +121,17 @@ impl WrappedParser {
                     .unwrap_throw();
                 let (named_path, var_type) = get_value_info(entity.serializer(), fp);
 
+                let mut value = match field_value {
+                    haste::fieldvalue::FieldValue::String(data) => {
+                        String::from_utf8_lossy(data).into_owned()
+                    }
+                    other => other.to_string(),
+                };
+
                 EntityFieldLi {
                     path: fp.iter().cloned().collect(),
                     named_path,
-                    value: field_value.to_string(),
+                    value,
                     encoded_as: var_type,
                     decoded_as: get_field_value_discriminant_name(field_value).to_string(),
                 }
```

encoding of data in `m_sHeroBuildSerialized` seems similar to https://github.com/SteamDatabase/GameTracking-Deadlock/blob/bd858135dac99651c618bedb14caccd7bbd76541/game/citadel/pak01_dir/cfg/valve_builds.kv3#L67, but not sure.

### CODE REVIEW

File: crates/haste_core/src/bitreader.rs [hunk 1]
```diff
@@ -292,6 +294,20 @@ impl<'a> BitReader<'a> {
         num_chars
     }
 
+    // same as read_string, but grows the buffer and appends to to it instead of overwritting.
```
Comment (raimannma) [inline crates/haste_core/src/bitreader.rs:297]:
```suggestion
    // same as read_string, but grows the buffer and appends to it instead of overwriting.
```

File: crates/haste_core/src/fieldvalue.rs [hunk 2]
```diff
@@ -16,14 +16,36 @@ pub enum FieldValue {
...
+    /// https://doc.rust-lang.org/stable/std/string/struct.String.html#utf-8.
+    ///
+    /// it doesn't not seem like thre's a reliable way to know which strings are treated as actual
+    /// strings and which ones are represent non-utf8 byte sequences to encode other data.
+    ///
+    /// also note that there's no data type in demo files that is dedicated specifically for
+    /// transfering bytes.
+    ///
+    /// use String::from_utf8_lossy in your code to convert this to an actual string, and handle
+    /// conversion errors.
```
Comment (raimannma) [inline crates/haste_core/src/fieldvalue.rs:35]:
```suggestion
    /// NOTE: not all strings are valid utf8 strings.
    ///
    /// deadlock has `CCitadelPlayerPawn` entity which has a `m_sHeroBuildSerialized` field of type
    /// `CUtlString` which, as the name suggests, contains serialized data which cannot be
    /// successfully converted to str/String.
    ///
    /// in c/cpp there's no enforcement on validation of strings. but in rust there is, see
    /// <https://doc.rust-lang.org/stable/std/string/struct.String.html#utf-8>.
    ///
    /// it does not seem like there is a reliable way to know which strings are treated as actual
    /// strings and which ones are represent non-utf8 byte sequences to encode other data.
    ///
    /// also note that there is no data type in demo files that is dedicated specifically for
    /// transferring bytes.
    ///
    /// use `String::from_utf8_lossy` in your code to convert this into an actual string, and handle
    /// conversion errors.
```

**Review by raimannma — COMMENTED** [review]
some typos I found while reading,

I got into some errors extracting the hero build, but I need to test a bit more to find the source.

**Comment by raimannma** [comment]
Also maybe we want to add a try into [u8] ?
```rs
impl TryInto<Box<[u8]>> for FieldValue {
    type Error = FieldValueConversionError;

    fn try_into(self) -> Result<Box<[u8]>, Self::Error> {
        match self {
            FieldValue::String(value) => Ok(value),
            _ => Err(FieldValueConversionError::IncompatibleTypeOrOutOfRangeInteger),
        }
    }
}
```

**Comment by raimannma** [comment]
Got it working @blukai 
fix seems good for me!
